Repository gkiga/mem-help, pull requests merged in 2020-11, with the labels that each got.

#47 MH-10 Reviews Foundation 1
  app/assets/stylesheets/reviews.scss
  app/controllers/requests_controller.rb
  app/controllers/reviews_controller.rb
  app/helpers/reviews_helper.rb
  app/models/review.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/reviews/_form.html.erb
  app/views/reviews/_review.json.jbuilder
  app/views/reviews/edit.html.erb
  app/views/reviews/index.html.erb
  app/views/reviews/index.json.jbuilder
  app/views/reviews/new.html.erb
  app/views/reviews/show.html.erb
  app/views/reviews/show.json.jbuilder
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20201031185158_create_reviews.rb
  db/migrate/20201031194347_add_user_id_to_reviews.rb
  db/schema.rb
  test/controllers/reviews_controller_test.rb
  test/fixtures/reviews.yml
  test/models/review_test.rb
  test/system/reviews_test.rb
Labels: enhancement

#50 MH-17: Review Notification
  app/assets/stylesheets/follows.scss
  app/controllers/follows_controller.rb
  app/controllers/requests_controller.rb
  app/controllers/reviews_controller.rb
  app/helpers/follows_helper.rb
  app/models/follow.rb
  app/models/my_notification.rb
  app/models/review.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  db/migrate/20201103051316_create_follows.rb
  db/migrate/20201103212528_add_review_fk_col_to_my_notifications.rb
  db/schema.rb
  test/controllers/follows_controller_test.rb
  test/fixtures/follows.yml
  test/fixtures/my_notifications.yml
  test/models/follow_test.rb
  test/models/my_notification_test.rb
Labels: enhancement

#51 MH-19: Follow Tutors
  app/assets/stylesheets/account_follows.scss
  app/controllers/account_follows_controller.rb
  app/controllers/users_controller.rb
  app/helpers/account_follows_helper.rb
  app/models/follow.rb
  app/models/my_notification.rb
  app/models/user.rb
  app/views/account_follows/index.html.erb
  app/views/layouts/application.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20201106011002_add_user_fk_col_to_my_notifications.rb
  db/schema.rb
  test/controllers/account_follows_controller_test.rb
  test/fixtures/my_notifications.yml
  test/models/my_notification_test.rb
Labels: enhancement

#54 MH-31 Implement action text
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/actiontext.scss
  app/javascript/packs/application.js
  app/models/message.rb
  app/models/my_notification.rb
  app/views/active_storage/blobs/_blob.html.erb
  app/views/messages/edit.html.erb
  app/views/messages/new.html.erb
  app/views/messages/show.html.erb
  config/initializers/html_sanitization.rb
  db/migrate/20201106041921_create_action_text_tables.action_text.rb
  db/schema.rb
  package.json
  test/fixtures/action_text/rich_texts.yml
  test/fixtures/my_notifications.yml
  test/models/my_notification_test.rb
  yarn.lock
Labels: enhancement

#55 MH-20: New Video Notification
  app/controllers/account_videos_controller.rb
  app/controllers/users_controller.rb
  app/controllers/videos_controller.rb
  app/models/my_notification.rb
  app/models/user.rb
  app/models/video.rb
  app/views/layouts/application.html.erb
  db/migrate/20201106204914_add_video_fk_col_to_my_notifications.rb
  db/schema.rb
  test/fixtures/my_notifications.yml
  test/models/my_notification_test.rb
Labels: enhancement

#59 MH-21 Global Request Organization Part 1
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/globals.scss
  app/controllers/globals_controller.rb
  app/models/global.rb
  app/views/globals/index.html.erb
  app/views/layouts/application.html.erb
  config/initializers/simple_form.rb
  config/locales/simple_form.en.yml
  config/routes.rb
  lib/templates/erb/scaffold/_form.html.erb
Labels: enhancement

#58 Mh 14 Enhanced Review (Part 2)
  app/controllers/reviews_controller.rb
  app/models/review.rb
  app/views/reviews/index.html.erb
  app/views/reviews/show.html.erb
  db/migrate/20201107194731_add_sender_name_to_reviews.rb
  db/schema.rb
  test/fixtures/reviews.yml
  test/models/review_test.rb
Labels: enhancement

#61 MH-15 notifications for Global Request
  app/controllers/globals_controller.rb
  app/models/global.rb
  app/models/my_notification.rb
  app/models/user.rb
  app/views/globals/index.html.erb
  app/views/layouts/application.html.erb
  app/views/requests/index.html.erb
  db/migrate/20201107194731_add_sender_name_to_reviews.rb
  db/migrate/20201109211222_add_global_fk_col_to_my_notifications.rb
  db/schema.rb
  test/fixtures/my_notifications.yml
  test/models/my_notification_test.rb
Labels: enhancement

#64 MH-22 Review Tutor/Teacher when request closed out.
  app/controllers/globals_controller.rb
  app/controllers/requests_controller.rb
  app/views/layouts/application.html.erb
  app/views/requests/show.html.erb
  app/views/reviews/_form.html.erb
  app/views/reviews/index.html.erb
  app/views/reviews/new.html.erb
  app/views/reviews/show.html.erb
  app/views/users/show.html.erb
  db/migrate/20201110213417_add_sender_name_to_reviews.rb
  db/schema.rb
Labels: enhancement

#66 MH-30 Video Thumbnails
  app/controllers/account_videos_controller.rb
  app/controllers/videos_controller.rb
  app/models/review.rb
  app/models/video.rb
  app/views/account_videos/new.html.erb
  app/views/users/show.html.erb
  app/views/videos/show.html.erb
  db/schema.rb
  test/fixtures/reviews.yml
  test/models/review_test.rb
Labels: enhancement

#68 MH-33 Global Request Personal View Index Revisited
  app/assets/stylesheets/global_listings.scss
  app/controllers/global_listings_controller.rb
  app/helpers/global_listings_helper.rb
  app/models/global.rb
  app/models/global_listing.rb
  app/models/user.rb
  app/views/global_listings/index.html.erb
  app/views/globals/show.html.erb
  app/views/layouts/application.html.erb
  app/views/requests/index.html.erb
  app/views/requests/show.html.erb
  config/routes.rb
  db/migrate/20201114165227_create_global_listings.rb
  db/migrate/20201114180225_add_global_listing_fk_col_to_globals.rb
  db/schema.rb
  test/controllers/global_listings_controller_test.rb
  test/fixtures/global_listings.yml
  test/fixtures/globals.yml
  test/models/global_listing_test.rb
  test/models/global_test.rb
Labels: enhancement

#70 MH-29 Updated Search Bar
  app/assets/stylesheets/application.scss
  app/controllers/static_pages_controller.rb
  app/models/review.rb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/globals/edit.html.erb
  app/views/globals/new.html.erb
  app/views/layouts/application.html.erb
  app/views/requests/edit.html.erb
  app/views/requests/new.html.erb
  app/views/static_pages/about.html.erb
  app/views/static_pages/home.html.erb
  app/views/videos/_form.html.erb
  app/views/videos/index.html.erb
  app/views/videos/show.html.erb
  config/routes.rb
  db/schema.rb
  test/fixtures/reviews.yml
  test/models/review_test.rb
Labels: enhancement

#71 MH-34 Video Reviews
  app/controllers/globals_controller.rb
  app/controllers/reviews_controller.rb
  app/controllers/videos_controller.rb
  app/models/review.rb
  app/models/video.rb
  app/views/reviews/_form.html.erb
  app/views/reviews/show.html.erb
  app/views/videos/_form.html.erb
  app/views/videos/show.html.erb
  db/migrate/20201115013149_addvkeytovideo.rb
  db/migrate/20201115024035_deletevkeyfromvideo.rb
  db/migrate/20201115024236_addvkeytoreviews.rb
  db/schema.rb
  test/fixtures/reviews.yml
  test/models/review_test.rb
Labels: enhancement

#73 HOTFIX: Notification Redirect
  app/controllers/my_notifications_controller.rb
Labels: bug

#79 SUPPORT: Commenting to messages and reviews
  app/controllers/messages_controller.rb
  app/controllers/reviews_controller.rb
  app/models/message.rb
  app/views/messages/edit.html.erb
  app/views/messages/index.html.erb
  app/views/messages/new.html.erb
  app/views/messages/show.html.erb
  app/views/reviews/edit.html.erb
  app/views/reviews/index.html.erb
Labels: documentation

#77 Support: Comments to Request Models, Misc.
  Gemfile
  app/controllers/application_controller.rb
  app/controllers/global_listings_controller.rb
  app/controllers/globals_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/requests_controller.rb
  app/controllers/reviews_controller.rb
  app/models/global.rb
  app/models/global_listing.rb
  app/models/request.rb
  app/models/review.rb
  app/models/user.rb
  app/views/global_listings/index.html.erb
  app/views/globals/edit.html.erb
  app/views/globals/index.html.erb
  app/views/globals/new.html.erb
  app/views/globals/show.html.erb
  app/views/requests/edit.html.erb
  app/views/requests/index.html.erb
  app/views/requests/new.html.erb
  app/views/requests/show.html.erb
  app/views/reviews/_form.html.erb
  app/views/reviews/index.html.erb
  app/views/reviews/show.html.erb
  app/views/users/show.html.erb
  app/views/videos/_form.html.erb
  app/views/videos/show.html.erb
  config/routes.rb
Labels: documentation

#81 HOTFIX: Fixed search result
  app/views/users/index.html.erb
Labels: bug

#83 SUPPORT: Commenting Videos, Notifications, and Follows
  app/controllers/account_follows_controller.rb
  app/controllers/account_videos_controller.rb
  app/controllers/follows_controller.rb
  app/controllers/my_notifications_controller.rb
  app/controllers/static_pages_controller.rb
  app/controllers/users_controller.rb
  app/controllers/videos_controller.rb
  app/models/my_notification.rb
  app/models/user.rb
  app/views/account_videos/new.html.erb
Labels: documentation
